--- 
- 
  gather_facts: true
  hosts: all
  name: "Windows Update"
  remote_user: administrator
  tasks: 
    - 
      name: "Running Windows Update"
      register: result
      win_updates: 
        category_names: 
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
          - DefinitionUpdates
    - 
      debug: var=result
    - win_reboot: 
      when: result.reboot_required
